### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by liang-hiwin** [mmotti/pihole-filter-lists#1]
2019-03-17 22:47:16 (219 KB/s) - “fetchFilterLists.sh” 已保存 [119841]

root@raspberrypi:/usr/local/bin# sudo chmod +x /usr/local/bin/fetchFilterLists.sh
root@raspberrypi:/usr/local/bin# fetchFilterLists.sh
/usr/local/bin/fetchFilterLists.sh:行7: 未预期的符号 `newline' 附近有语法错误
/usr/local/bin/fetchFilterLists.sh:行7: `<!DOCTYPE html>'
root@raspberrypi:/usr/local/bin#

**Comment by mmotti** [comment]
That's odd... I can't seem to replicate that here.

Perhaps try download the script directly on the Pi:
`sudo wget -qO /usr/local/bin/fetchFilterLists.sh https://raw.githubusercontent.com/mmotti/pihole-filter-lists/master/fetchFilterLists.sh`

Then allow it to execute:
`sudo chmod +x /usr/local/bin/fetchFilterLists.sh`

Then run it:
`fetchFilterLists.sh`

My output:

```
[i] Fetching hosts
[i] 32035 hosts fetched
[i] Parsing existing dnsmasq configs
[i] Determining output format
[i] Removing unnecessary subdomains
[i] Running regex removals from /etc/pihole/regex.list
[i] 1572 hosts regex removed
[i] Checking for conflicts against existing config
[i] 46 hosts matched against existing conf entries
[i] Processing whitelist
[i] 1 conflicts with whitelist
[i] Outputting 29941 hosts to /etc/dnsmasq.d/filter-lists.conf
[i] Restarting Pihole service
```
