### ISSUE TITLE
Blockingmode=NODATA leads to “bad address”

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [mmotti/pihole-filter-lists#2]
When you set the blockingmode to NODATA and run the script, pihole-FTL refuses to start staying 

    dnsmasq: bad address at line 1 of /etc/dnsmasq.d/filter_lists.conf

Changing the blocking mode or modifying the filter_list.conf by hand fixes the problem.
Looks like dnsmasq does not recognize NODATA in address= fields.

**Comment by mmotti** [comment]
Thanks for reporting this.

It looks like NODATA has been added as a blocking method quite recently.

Basically, the switch/case didn't have a default value to fallback on should it encounter something that it didn't recognise.

I can't find any DNSMASQ documentation for the syntax to return NODATA, so I have let it fall back to NULL for now (`address=/test.com/#`)

It should at least resolve the issue with FTL failing to start, though.

**Comment by Unkn0wn-MDCLXIV** [comment]
That’s what I did, i hope we find the proper syntax for NODATA soon.

**Comment by mmotti** [comment]
Sadly I don't think there's a way at present.

There are options for Null, IPv6 NODATA, IP(v4+v6) and nxdomain but not NODATA.

Will add in if I can find a way to do so in future.

Edit: if you update to the latest script and run again, you can keep your blocking mode set to NODATA for gravity domains. The wildcards will fall back to null automatically :-)
