### ISSUE TITLE
Invalid range end

### ISSUE THREAD

**Issue by GokulG07** [mmotti/pihole-filter-lists#4]
pi@raspberrypi:~ $ sudo fetchFilterLists.sh                                                    [i] Selected filter sources: adguarddns,easylist,easyprivacy,nocoin
[i] Fetching domains
[i] Parsing existing wildcard config (DNSMASQ)
[i] Cleaning domains
[i] Removing regex.list conflicts
grep: /dev/fd/63:17: Invalid range end
[i] There are no domains to process after regex removals.

**Comment by mmotti** [comment]
Hi,

It looks like you potentially have an invalid regexp specified in your configuration.

Please could you confirm the regexps you are using? If you are still on the master branch of Pi-hole you can use `cat /etc/pihole/regex.list` to output them.

**Comment by GokulG07** [comment]
Thanks for responding... Here it is

pi@raspberrypi:~ $ cat /etc/pihole/regex.list                                                  ^(.+[-_.])??adse?rv(er?|ice)?s?[0-9]*[-.]
^(.+[-_.])??m?ad[sxv]?[0-9]*[-_.]
^(.+[-_.])??xn--
^adim(age|g)s?[0-9]*[-_.]
^adtrack(er|ing)?[0-9]*[-.]
^advert(s|is(ing|ements?))?[0-9]*[-_.]
^aff(iliat(es?|ion))?[-.]
^analytics?[-.]
^banners?[-.]
^beacons?[0-9]*[-.]
^count(ers?)?[0-9]*[-.]
^pixels?[-.]
^stat(s|istics)?[0-9]*[-.]
^telemetry[-.]
^track(ers?|ing)?[0-9]*[-.]
^traff(ic)?[-.]
play.google.com##div[style="background-color: rgb(90, 90, 90);"]:has-text(Cookie)


https://github.com/mmotti/pihole-regex

**Comment by mmotti** [comment]
Your problem is **play.google.com##div[style="background-color: rgb(90, 90, 90);"]:has-text(Cookie)**

This looks like a filter patter which is not suitable to add as a regexp to Pi-hole. Remove that, re-run the script and you should be OK.

```
Running: ^(.+[-_.])??adse?rv(er?|ice)?s?[0-9]*[-.]
Against: test.com
No match

Running: ^(.+[-_.])??m?ad[sxv]?[0-9]*[-_.]
Against: test.com
No match

Running: ^(.+[-_.])??xn--^adim(age|g)s?[0-9]*[-_.]
Against: test.com
No match

Running: ^adtrack(er|ing)?[0-9]*[-.]^
Against: test.com
No match

Running: advert(s|is(ing|ements?))?[0-9]*[-_.]^
Against: test.com
No match

Running: aff(iliat(es?|ion))?[-.]^
Against: test.com
No match

Running: analytics?[-.]^
Against: test.com
No match

Running: banners?[-.]^
Against: test.com
No match

Running: beacons?[0-9]*[-.]^
Against: test.com
No match

Running: count(ers?)?[0-9]*[-.]^
Against: test.com
No match

Running: pixels?[-.]^stat(s|istics)?[0-9]*[-.]^
Against: test.com
No match

Running: telemetry[-.]^track(ers?|ing)?[0-9]*[-.]^
Against: test.com
No match

Running: traff(ic)?[-.]
Against: test.com
No match

Running: play.google.com##div[style="background-color: rgb(90, 90, 90);"]:has-text(Cookie)
Against: test.com
Error with regexp
```

**Comment by GokulG07** [comment]
Need help i'm not able to delete from the regex menu it is some how coming back.. Also tried restarting FTL.

**Comment by mmotti** [comment]
As you are exclusively using my regex list, you could do the following:
1. `sudo bash -c '> /etc/pihole/regex.list'`
2. `sudo service pihole-FTL restart`
3. `curl -sSl https://raw.githubusercontent.com/mmotti/pihole-regex/master/install.sh | bash `

**Comment by GokulG07** [comment]
Yes all working fine... Thanks a lot...
